// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCS_ClineName_CodeFirstApproach.DbConnect;

#nullable disable

namespace TCS_ClineName_CodeFirstApproach.Migrations
{
    [DbContext(typeof(EmployeeContext))]
    [Migration("20241112003647_rayudu")]
    partial class rayudu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TCS_ClineName_CodeFirstApproach.Employee", b =>
                {
                    b.Property<int>("empid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("empid"));

                    b.Property<string>("empname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("empsalary")
                        .HasColumnType("int");

                    b.HasKey("empid");

                    b.ToTable("employees");
                });

            modelBuilder.Entity("TCS_ClineName_CodeFirstApproach.Entities.Departement", b =>
                {
                    b.Property<int>("deptid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("deptid"));

                    b.Property<string>("deptlocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("deptname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("deptid");

                    b.ToTable("departements");
                });
#pragma warning restore 612, 618
        }
    }
}
